---
kind: pipeline
name: NGenToD GCC ARM64

clone:
  depth: 1

steps:
- name: val
  image: archlinux:base-devel
  environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
  commands:
    - "export GH_TOKEN"
    - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
    - pacman -Sy base-devel wget clang cmake git libc++ lld lldb ninja --noconfirm
    - ./build-gcc.sh -a arm64
    - ./build-lld.sh -a arm64
    - ./push.sh

---
kind: pipeline
name: NGenToD GCC ARM32

clone:
  depth: 1     

steps:
- name: val    
  image: archlinux:base-devel
  environment: 
      GH_TOKEN:
        from_secret: GH_TOKEN
  commands:    
    - "export GH_TOKEN"
    - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
    - pacman -Sy base-devel wget clang cmake git libc++ lld lldb ninja --noconfirm
    - ./build-gcc.sh -a arm
    - ./build-lld.sh -a arm
    - ./push.sh

